name: Deploy Advanced-Feature Weather Application

on:
  push:
    branches: [advanced-version]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4.2.2

      - name: setup Node js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: installing the dependencies
        run: npm install

      - name: build the project
        run: npm run build

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
